let token='__TOKEN__';const $=id=>document.getElementById(id);let current;let busy=false;let feedFrozen=false;
async function api(url,body,method=body===undefined?'GET':'POST'){const request=()=>fetch(url,{method,headers:{'x-watchdog-token':token},body:body===undefined?undefined:body});let response=await request();if(response.status===403){const source=await(await fetch('/app.js',{cache:'no-store'})).text();const fresh=/let token='([^']+)'/.exec(source);if(fresh&&fresh[1]!==token){token=fresh[1];response=await request();}}const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
function node(tag,text,parent){const el=document.createElement(tag);el.textContent=text;parent.append(el);return el;}
async function refresh(){current=await api('/status');$('status').textContent=`${current.state} · ${current.receiverMode||''} · WB M: ${current.transportStatus||'Not configured'} · ${current.paused?'Paused':'Watching'} · ${current.pullCount} parsed pulls · ${current.messageCount} captured messages${current.error?' · '+current.error:''}`;$('qr').hidden=!current.qr;if(current.qr)$('qr').src=current.qr;
 renderLiveFeed();
 $('resume').disabled=busy||current.state!=='Connected'||!current.channels.length||!current.paused;$('pause').disabled=busy||current.paused;$('save').disabled=busy||!current.chats.length;$('connect').disabled=busy||['Connecting','Syncing WhatsApp','Connected','Scan QR'].includes(current.state);
 if(!$('groups').contains(document.activeElement)&&$('groups').dataset.signature!==JSON.stringify(current.chats)){$('groups').replaceChildren();$('groups').dataset.signature=JSON.stringify(current.chats);for(const chat of current.chats){const div=node('div','',$('groups'));div.className='group';const check=node('input','',div);check.type='checkbox';check.dataset.id=chat.id;const saved=current.channels.find(c=>c.id===chat.id);check.checked=!!saved;node('span',chat.name,div);const well=node('input','',div);well.type='text';well.placeholder='Default well';well.value=saved?.options.defaultWell||'';const label=node('label','',div),def=node('input','',label);def.type='checkbox';def.checked=saved?.options.defaultBbls===165;node('span',' Missing barrels = 165',label);}}
 $('exports').replaceChildren();for(const c of current.channels){const b=node('button','Download '+c.name,$('exports'));b.onclick=()=>download(c.id,c.name);}
 if($('queue').dataset.signature===JSON.stringify([current.messages,current.deliveries]))return;$('queue').dataset.signature=JSON.stringify([current.messages,current.deliveries]);$('queue').replaceChildren();for(const m of current.messages.slice(0,25)){const article=node('article','',$('queue'));node('strong',`${current.channels.find(c=>c.id===m.channel)?.name||m.channel} ${m.deleted?'· Deleted':m.edited?'· Edited':''}`,article);for(const row of m.rows){node('p',`${row.wellName||'Unknown well'} · ${row.dateTimeUTC?new Date(row.dateTimeUTC).toLocaleString('en-US',{timeZone:'America/Chicago'}):'Time needs review'} · top ${row.tankLevelFeet??'?'} ft · ${row.bblsTaken??'?'} bbl`,article);if(current.deliveries?.[row.id])node('p','WB M: '+current.deliveries[row.id].status,article);if(row.issues.length)node('p',row.issues.join('; '),article).className='warn';}for(const n of m.notices)node('p',n.reason,article).className='warn';const details=node('details','',article);node('summary','Original post',details);node('pre',m.chat,details);}}
async function action(fn,button,message='Done'){if(busy)return;busy=true;const label=button?.textContent;if(button){button.disabled=true;button.textContent='Working...';}$('notice').textContent='Working...';try{await fn();await refresh();if($('notice').textContent==='Working...')$('notice').textContent=message;}catch(e){$('notice').textContent='Failed: '+e.message;}finally{busy=false;if(button){button.disabled=false;button.textContent=label;}}}
for(const route of ['connect','resume','pause','stop','refresh-groups'])$(route).onclick=()=>action(()=>api('/'+route,''),$(route),{'connect':'Connection requested. Watch the status above.','resume':'Watching the selected groups.','pause':'Capture paused.','stop':'Connection stopped.','refresh-groups':'Group refresh requested. Check the connection status above.'}[route]);
$('save').onclick=()=>action(()=>api('/channels',JSON.stringify([...$('groups').children].filter(d=>d.children[0].checked).map(d=>({id:d.children[0].dataset.id,defaultWell:d.children[2].value,defaultBbls:d.children[3].querySelector('input').checked?165:undefined})))), $('save'), 'Group selection saved.');
$('replay').onclick=()=>action(async()=>{const file=$('file').files[0];if(!file)throw Error('Choose a ZIP or TXT');const p=new URLSearchParams({channel:$('channel').value,well:$('well').value,default165:$('default165').checked});const result=await api('/replay?'+p,await file.arrayBuffer());$('notice').textContent=`${result.added} messages added; ${result.duplicates} duplicates skipped.`;},$('replay'));
async function download(channel,name){const r=await fetch('/export?'+new URLSearchParams({channel}),{headers:{'x-watchdog-token':token}});if(!r.ok)throw Error('Download failed');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name.replace(/[^a-z0-9_-]/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
refresh().catch(e=>$('notice').textContent=e.message);setInterval(()=>refresh().catch(e=>$('notice').textContent=e.message),4000);

function renderLiveFeed(){
 const filter=$('live-filter');const groupSignature=JSON.stringify(current.channels.map(c=>[c.id,c.name]));if(filter.dataset.signature!==groupSignature){const selected=filter.value;filter.replaceChildren();const all=node('option','All watched groups',filter);all.value='';for(const c of current.channels){const option=node('option',c.name,filter);option.value=c.id;}filter.value=selected;filter.dataset.signature=groupSignature;}
 $('live-health').textContent=`${current.paused?'Capture paused':'Checking every four seconds'} · Last receiver check: ${current.lastReceiverCheck?new Date(current.lastReceiverCheck).toLocaleTimeString('en-US',{timeZone:'America/Chicago'}):'waiting'}${feedFrozen?' · Display frozen; capture continues':''}`;
 if(feedFrozen)return;
 const groups=current.channels.filter(c=>!filter.value||c.id===filter.value);
 const container=$('live-feed');const layout=JSON.stringify(groups.map(c=>[c.id,c.name]));
 if(container.dataset.layout!==layout){container.replaceChildren();container.dataset.layout=layout;for(const group of groups){const panel=node('section','',container);panel.className='live-group';panel.dataset.channel=group.id;node('h3',group.name,panel);const list=node('div','',panel);list.className='group-posts';list.setAttribute('role','log');list.setAttribute('aria-live','polite');list.setAttribute('aria-label',group.name+' live posts');list.tabIndex=0;}}
 if(!groups.length){container.textContent='Choose watched groups to see their live posts.';return;}
 for(const panel of container.children){const posts=(current.livePosts||[]).filter(m=>m.channel===panel.dataset.channel).slice(0,25);const list=panel.querySelector('.group-posts');const signature=JSON.stringify(posts.map(post=>[post,post.rows.map(row=>current.deliveries?.[row.id])]));if(list.dataset.signature===signature)continue;list.dataset.signature=signature;const oldTop=list.scrollTop,oldHeight=list.scrollHeight;list.replaceChildren();
 if(!posts.length)node('p','Waiting for live posts from this group.',list);
 for(const post of posts){const card=node('article','',list);node('p',(post.author||'Driver')+' · '+new Date(post.postedAt||post.updatedAt).toLocaleString('en-US',{timeZone:'America/Chicago'})+(post.edited?' · Edited':'')+(post.deleted?' · Deleted':''),card).className='post-meta';node('pre',post.deleted?'Post deleted':post.body||post.chat,card);const statuses=post.rows.map(row=>current.deliveries?.[row.id]?.status||((current.enabledAt&&(Date.parse(row.postedAt)<current.enabledAt||Date.parse(row.dateTimeUTC)<current.enabledAt))?'before activation · not sent':(row.issues.length)?'review':'waiting'));const reasons=post.rows.flatMap(row=>current.deliveries?.[row.id]?.issues||row.issues||[]);
 node('p',post.deleted?'Held: deleted post':post.edited?'Held: edited post needs review':statuses.length?'WB M: '+[...new Set(statuses)].join(', '):post.notices.length?'Tank setup notice: review':'Chat post · not a pull',card).className='post-status';if(reasons.length)node('p',[...new Set(reasons)].join('; '),card).className='warn';}
 list.scrollTop=oldTop>0?Math.max(0,oldTop+list.scrollHeight-oldHeight):0;
 }

}
$('live-filter').onchange=()=>renderLiveFeed();$('freeze-feed').onclick=()=>{feedFrozen=!feedFrozen;$('freeze-feed').textContent=feedFrozen?'Resume feed':'Freeze feed';renderLiveFeed();};
