let token='__TOKEN__';const $=id=>document.getElementById(id);let current;let busy=false;let feedFrozen=false;
async function api(url,body,method=body===undefined?'GET':'POST'){const request=()=>fetch(url,{method,headers:{'x-watchdog-token':token},body:body===undefined?undefined:body});let response=await request();if(response.status===403){const source=await(await fetch('/app.js',{cache:'no-store'})).text();const fresh=/let token='([^']+)'/.exec(source);if(fresh&&fresh[1]!==token){token=fresh[1];response=await request();}}const data=await response.json();if(!response.ok)throw Error(data.error);return data;}
function node(tag,text,parent){const el=document.createElement(tag);el.textContent=text;parent.append(el);return el;}
async function refresh(){current=await api('/status');$('status').textContent=`${current.state} · ${current.receiverMode||''} · WB M: ${current.transportStatus||'Not configured'} · ${current.paused?'Paused':'Watching'} · ${current.pullCount} parsed pulls · ${current.messageCount} captured messages${current.error?' · '+current.error:''}`;$('qr').hidden=!current.qr;if(current.qr)$('qr').src=current.qr;
 renderReviews();
 renderAlertSettings();
 renderBarrelPolicy();
 renderBarrelTest();
 renderLiveFeed();
 renderReviews();
 $('resume').disabled=busy||current.state!=='Connected'||!current.channels.length||!current.paused;$('pause').disabled=busy||current.paused;$('save').disabled=busy||!current.chats.length;$('connect').disabled=busy||['Connecting','Syncing WhatsApp','Connected','Scan QR'].includes(current.state);
 if(!$('groups').contains(document.activeElement)&&$('groups').dataset.signature!==JSON.stringify(current.chats)){$('groups').replaceChildren();$('groups').dataset.signature=JSON.stringify(current.chats);for(const chat of current.chats){const div=node('div','',$('groups'));div.className='group';const check=node('input','',div);check.type='checkbox';check.dataset.id=chat.id;const saved=current.channels.find(c=>c.id===chat.id);check.checked=!!saved;node('span',chat.name,div);const well=node('input','',div);well.type='text';well.placeholder='Default well';well.value=saved?.options.defaultWell||'';const label=node('label','',div),def=node('input','',label);def.type='checkbox';def.checked=Number(saved?.options.defaultBbls)>0;node('span',' Missing barrels fallback: ',label);const amount=node('input','',label);amount.type='number';amount.min='1';amount.max='1000';amount.step='any';amount.value=saved?.options.defaultBbls||165;amount.setAttribute('aria-label','Missing barrels fallback for '+chat.name);amount.disabled=!def.checked;def.onchange=()=>amount.disabled=!def.checked;}}
 $('exports').replaceChildren();for(const c of current.channels){const b=node('button','Download '+c.name,$('exports'));b.onclick=()=>download(c.id,c.name);}
 if($('queue').dataset.signature===JSON.stringify([current.messages,current.deliveries]))return;$('queue').dataset.signature=JSON.stringify([current.messages,current.deliveries]);$('queue').replaceChildren();for(const m of current.messages.slice(0,25)){const article=node('article','',$('queue'));node('strong',`${current.channels.find(c=>c.id===m.channel)?.name||m.channel} ${m.deleted?'· Deleted':m.edited?'· Edited':''}`,article);for(const row of m.rows){node('p',`${row.wellName||'Unknown well'} · ${row.dateTimeUTC?new Date(row.dateTimeUTC).toLocaleString('en-US',{timeZone:'America/Chicago'}):'Time needs review'} · top ${row.tankLevelFeet??'?'} ft · ${row.bblsTaken??'?'} bbl`,article);if(current.deliveries?.[row.id])node('p','WB M: '+current.deliveries[row.id].status,article);if(row.issues.length)node('p',row.issues.join('; '),article).className='warn';}for(const n of m.notices)node('p',n.reason,article).className='warn';const details=node('details','',article);node('summary','Original post',details);node('pre',m.chat,details);}}
async function action(fn,button,message='Done',feedback){if(busy){if(feedback)feedback.textContent='Another action is processing; try again in a moment.';return;}busy=true;const label=button?.textContent;if(button){button.disabled=true;button.textContent='Working...';}$('notice').textContent='Working...';if(feedback)feedback.textContent='Working...';try{await fn();await refresh();if($('notice').textContent==='Working...')$('notice').textContent=message;if(feedback)feedback.textContent=message;}catch(e){$('notice').textContent='Failed: '+e.message;if(feedback)feedback.textContent='Failed: '+e.message;}finally{busy=false;if(button){button.disabled=false;button.textContent=label;button.blur();}}}
for(const route of ['connect','resume','pause','stop','refresh-groups'])$(route).onclick=()=>action(()=>api('/'+route,''),$(route),{'connect':'Connection requested. Watch the status above.','resume':'Watching the selected groups.','pause':'Capture paused.','stop':'Connection stopped.','refresh-groups':'Group refresh requested. Check the connection status above.'}[route]);
$('save').onclick=()=>action(()=>api('/channels',JSON.stringify([...$('groups').children].filter(d=>d.children[0].checked).map(d=>({id:d.children[0].dataset.id,defaultWell:d.children[2].value,defaultBbls:d.children[3].querySelector('input[type=checkbox]').checked?Number(d.children[3].querySelector('input[type=number]').value):undefined})))), $('save'), 'Group selection saved.');
$('replay').onclick=()=>action(async()=>{const file=$('file').files[0];if(!file)throw Error('Choose a ZIP or TXT');const p=new URLSearchParams({channel:$('channel').value,well:$('well').value,default165:$('default165').checked});const result=await api('/replay?'+p,await file.arrayBuffer());$('notice').textContent=`${result.added} messages added; ${result.duplicates} duplicates skipped.`;},$('replay'));
async function download(channel,name){const r=await fetch('/export?'+new URLSearchParams({channel}),{headers:{'x-watchdog-token':token}});if(!r.ok)throw Error('Download failed');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=name.replace(/[^a-z0-9_-]/gi,'_')+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
refresh().catch(e=>$('notice').textContent=e.message);setInterval(()=>refresh().catch(e=>$('notice').textContent=e.message),4000);

function renderLiveFeed(){
 const filter=$('live-filter');const groupSignature=JSON.stringify(current.channels.map(c=>[c.id,c.name]));if(filter.dataset.signature!==groupSignature){const selected=filter.value;filter.replaceChildren();const all=node('option','All watched groups',filter);all.value='';for(const c of current.channels){const option=node('option',c.name,filter);option.value=c.id;}filter.value=selected;filter.dataset.signature=groupSignature;}
 $('live-health').textContent=`${current.paused?'Capture paused':'Checking every four seconds'} · Last receiver check: ${current.lastReceiverCheck?new Date(current.lastReceiverCheck).toLocaleTimeString('en-US',{timeZone:'America/Chicago'}):'waiting'}${feedFrozen?' · Display frozen; capture continues':''}`;
 if(feedFrozen||$('live-feed').contains(document.activeElement))return;
 const selectedGroups=current.channels.filter(c=>!filter.value||c.id===filter.value);
 const lifecycle=current.wellLifecycle||[];const archived=new Set(lifecycle.filter(w=>w.archive).map(w=>w.wellName));
 const groups=selectedGroups.filter(c=>{const wells=lifecycle.filter(w=>w.channels?.includes(c.id));return !wells.length||wells.some(w=>!w.archive);});
 const archives=$('archived-wells');const archiveSignature=JSON.stringify(lifecycle);if(!archives.contains(document.activeElement)&&archives.dataset.signature!==archiveSignature){archives.dataset.signature=archiveSignature;archives.replaceChildren();if(archived.size){const details=node('details','',archives);node('summary','Archived wells ('+archived.size+')',details);for(const w of lifecycle.filter(w=>w.archive)){const group=current.channels.find(c=>w.channels?.includes(c.id));if(group){const panel=node('section','',details);panel.className='live-group';node('h3',w.wellName+' · '+group.name,panel);renderWellControls(panel,group,w.wellName);}}}}
 const container=$('live-feed');const layout=JSON.stringify([groups.map(c=>[c.id,c.name]),current.wellLifecycle]);
 if(container.dataset.layout!==layout){container.replaceChildren();container.dataset.layout=layout;for(const group of groups){const panel=node('section','',container);panel.className='live-group';panel.dataset.channel=group.id;node('h3',group.name,panel);renderWellControls(panel,group);const list=node('div','',panel);list.className='group-posts';list.setAttribute('role','log');list.setAttribute('aria-live','polite');list.setAttribute('aria-label',group.name+' live posts');list.tabIndex=0;}}
 if(!groups.length){container.textContent=selectedGroups.length?'No active wells in this group. Saved posts are in Archived wells.':'Choose watched groups to see their live posts.';return;}
 for(const panel of container.children){const posts=(current.livePosts||[]).filter(m=>m.channel===panel.dataset.channel&&(!m.rows.length||m.rows.some(r=>!archived.has(r.wellName)))).slice(0,25);const list=panel.querySelector(':scope > .group-posts');const signature=JSON.stringify(posts.map(post=>[post,post.rows.map(row=>current.deliveries?.[row.id])]));if(list.dataset.signature===signature)continue;list.dataset.signature=signature;const oldTop=list.scrollTop,oldHeight=list.scrollHeight;list.replaceChildren();
 if(!posts.length)node('p','Waiting for live posts from this group.',list);
 for(const post of posts){const card=node('article','',list);node('p',(post.author||'Driver')+' · '+new Date(post.postedAt||post.updatedAt).toLocaleString('en-US',{timeZone:'America/Chicago'})+(post.edited?' · Edited':'')+(post.deleted?' · Deleted':''),card).className='post-meta';node('pre',post.deleted?'Post deleted':post.body||post.chat,card);const statuses=post.rows.map(row=>(current.deliveries?.[row.id]?.alreadyRecorded?'already recorded in app':current.deliveries?.[row.id]?.status)||((current.enabledAt&&(Date.parse(row.postedAt)<current.enabledAt||Date.parse(row.dateTimeUTC)<current.enabledAt))?'before activation · not sent':(row.issues.length)?'review':'waiting'));const reasons=post.rows.flatMap(row=>current.deliveries?.[row.id]?.issues||row.issues||[]);
 node('p',post.deleted?'Held: deleted post':post.edited?'Held: edited post needs review':statuses.length?'WB M: '+[...new Set(statuses)].join(', '):post.notices.length?'Tank setup notice: review':'Chat post · not a pull',card).className='post-status';if(reasons.length)node('p',[...new Set(reasons)].join('; '),card).className='warn';for(const row of post.rows)reviewControls(row,post,card);}
 list.scrollTop=oldTop>0?Math.max(0,oldTop+list.scrollHeight-oldHeight):0;
 }

}
$('live-filter').onchange=()=>renderLiveFeed();$('freeze-feed').onclick=()=>{feedFrozen=!feedFrozen;$('freeze-feed').textContent=feedFrozen?'Resume feed':'Freeze feed';renderLiveFeed();};

function reviewControls(row,post,card){
 row={...row,...current.deliveries?.[row.id]?.measurements};
 const diagnostic=current.deliveries?.[row.id];if(diagnostic?.estimate){const e=diagnostic.estimate;node('p',`Barrels: ${row.bblsTaken} (${diagnostic.barrelSource==='estimated'?'estimated':diagnostic.barrelSource==='default'?'assumed default':'written'}). Level estimate: ${e.estimatedBbls!==null?e.estimatedBbls+' bbl; range ':''}${e.lowBbls}${e.highBbls!==null?'–'+e.highBbls:''} bbl. Uses 20-minute estimated loading (range 10–30 min).`,card);}

 const delivery=current.deliveries?.[row.id];if(!(delivery?.status==='review'||delivery?.needsReview)||!canReviewPost(post,row.id))return;
 row={...row,...delivery.measurements};
 const box=node('div','',card);node('p',row.wellName+' · Review measurement time (Central)',box);
 const time=node('input','',box);time.type='datetime-local';const parsed=Date.parse(delivery.review?.dateTimeUTC||row.dateTimeUTC);const parts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(Number.isFinite(parsed)?parsed:Date.now())).map(p=>[p.type,p.value]));time.value=Number.isFinite(parsed)?parts.year+'-'+parts.month+'-'+parts.day+'T'+parts.hour+':'+parts.minute:'';time.setAttribute('aria-label','Measurement time for '+row.wellName);
 const measurements={};for(const [key,label,value] of (current.reviewCorrectionsEnabled?[['tankLevelFeet','Top level (decimal feet)',row.tankLevelFeet],['bottomLevelFeet','Bottom level (decimal feet, optional)',row.bottomLevelFeet],['bblsTaken','Barrels',row.bblsTaken]]:[])){const field=node('input','',box);field.type='number';field.step='any';field.min='0';field.value=value??'';field.placeholder=label;field.setAttribute('aria-label',label+' for '+row.wellName);measurements[key]=field;}
 const reason=node('input','',box);reason.placeholder='Required reason (at least 3 characters)';reason.maxLength=300;reason.setAttribute('aria-label','Review reason for '+row.wellName);
 const feedback=node('p','',box);feedback.setAttribute('role','status');feedback.setAttribute('aria-live','polite');
 for(const [decision,label] of [['confirm',delivery.identity?'Confirm / correct existing pull':'Confirm and send'],['exclude',delivery.identity?'Dismiss review; keep pull':'Exclude']]){const button=node('button',label,box);button.onclick=()=>action(()=>{if(reason.value.trim().length<3)throw Error('Enter a review reason (at least 3 characters).');return api('/review',JSON.stringify({rowId:row.id,decision,time:time.value,reason:reason.value,corrections:Object.fromEntries(Object.entries(measurements).map(([key,field])=>[key,field.value===''?null:Number(field.value)]))}));},button,decision==='confirm'?'Correction submitted; waiting for WB M to finish updating the same pull.':'Review dismissed. An already sent pull remains recorded.',feedback);}
}

function renderBarrelTest(){
 const entries=(current.livePosts||[]).flatMap(post=>post.rows.map(row=>({post,row,delivery:current.deliveries?.[row.id]}))).filter(e=>/^Gunslinger (3|5)$/.test(e.row.wellName)&&(e.delivery?.estimate||Date.parse(e.post.postedAt)>Date.now()-86400000)).sort((a,b)=>Date.parse(b.row.dateTimeUTC)-Date.parse(a.row.dateTimeUTC));
 const body=$('barrel-test-rows');const signature=JSON.stringify(entries);if(body.dataset.signature===signature)return;body.dataset.signature=signature;body.replaceChildren();
 $('barrel-test-summary').textContent=entries.length?entries.length+' captured pulls · '+entries.filter(e=>e.delivery?.estimate).length+' estimates · updates every four seconds. Missing estimates are shown explicitly; older pulls are not resent.':'Waiting for the next Gunslinger pull processed with the estimator. Older completed pulls are not changed or resent.';
 for(const {post,row,delivery:d} of entries){const e=d?.estimate,tr=node('tr','',body);if(!e){const parsed=Date.parse(row.dateTimeUTC);for(const value of [Number.isFinite(parsed)?new Date(parsed).toLocaleString('en-US',{timeZone:'America/Chicago'}):'Time needs review',row.wellName+' / '+(post.author||row.author||'Driver'),row.bblsTaken==null?'Missing barrels':row.bblsTaken+' bbl (source not recorded)', '—','No estimate recorded','—','—',d?.status||'waiting'])node('td',value,tr);continue;}const point=e.estimatedBbls;const diff=point==null?null:point-row.bblsTaken;
 const cells=[new Date(d.review?.dateTimeUTC||row.dateTimeUTC).toLocaleString('en-US',{timeZone:'America/Chicago'}),row.wellName+' / '+(post.author||row.author||'Driver'),(d.measurements?.bblsTaken??row.bblsTaken)+' ('+(d.barrelSource==='estimated'?'estimated':d.barrelSource==='default'?'assumed':'written')+')',e.observedDropBbls+' bbl',point==null?'AFR unavailable':point+' bbl',e.highBbls==null?'No production estimate':e.lowBbls+'–'+e.highBbls+' bbl',diff==null?'—':(diff>0?'+':'')+diff+' bbl',d.status];
 for(const value of cells)node('td',value,tr);
 }
}


function renderWellControls(panel,group,archivedWell){
 const wells=(current.wellLifecycle||[]).filter(w=>w.channels?.includes(group.id)&&(archivedWell?w.wellName===archivedWell:!w.archive));
 const box=node('div','',panel);box.className='well-controls';
 node('p','Ending monitoring stops WB M’s predicted inflow; it does not mean the well stopped producing.',box);
 const select=node('select','',box);select.setAttribute('aria-label','Well to manage in '+group.name);
 for(const w of wells){const option=node('option',w.wellName,select);option.value=w.wellName;}
 const detail=node('div','',box);
 const draw=()=>{detail.replaceChildren();const w=wells.find(w=>w.wellName===select.value);if(!w){select.hidden=true;node('p','No wells configured for WB M delivery in this group yet.',detail);return;}
 node('p',w.archive?'Monitoring ended · '+(w.state==='archived'?'WB M predicted inflow stopped':'WB M confirmation pending'):'Monitoring active',detail);
 if(w.archive){node('p',w.archive.reason,detail);node('p','Archived '+new Date(w.archive.at).toLocaleString('en-US',{timeZone:'America/Chicago'}),detail);}
 const reason=node('input','',detail);reason.placeholder='Reason for ending monitoring';reason.maxLength=300;reason.value=w.archive?.reason||'';reason.hidden=!!w.archive;reason.setAttribute('aria-label','Stop reason for '+w.wellName);
 if(w.state!=='archived'){const button=node('button',w.archive?'Retry stop command':'Stop and archive',detail);button.setAttribute('aria-label','Stop and archive '+w.wellName);button.onclick=()=>action(()=>api('/stop-well',JSON.stringify({wellName:w.wellName,reason:reason.value})),button,'Monitoring ended; waiting for WB M to confirm predicted inflow stopped.');}
 const archive=node('details','',detail);node('summary','Saved posts / archive for '+w.wellName,archive);const list=node('div','',archive);list.className='group-posts';
 const posts=(current.messages||[]).filter(p=>p.channel===group.id&&p.rows.some(r=>r.wellName===w.wellName));node('p',posts.length+' saved posts. Starting again will require a new monitoring run; WB M stays marked down until manually unchecked.',list);for(const p of posts){const card=node('article','',list);node('pre',p.chat,card);}
 };select.onchange=draw;draw();
}

function openReviews(channel=''){ $('review-filter').value=channel;renderReviews();$('review-inbox').scrollIntoView({behavior:'smooth'});}
function reviewBadge(parent,channel){const count=(current.reviewInbox||[]).filter(e=>e.post.channel===channel).length;let badge=parent.querySelector('.review-badge');if(!badge){badge=node('button','',parent);badge.className='review-badge';badge.onclick=()=>openReviews(channel);}badge.textContent=count+' need review';badge.hidden=!count;}
function renderReviews(){
 const entries=current.reviewInbox||[],filter=$('review-filter');
 document.title=(entries.length?'('+entries.length+' reviews) ':'')+'WellBuilt Watchdog';
 const banner=$('review-banner');banner.replaceChildren();const link=node('a',entries.length+' pulls need review',banner);link.href='#review-inbox';link.onclick=()=>openReviews();banner.className=entries.length?'review-alert':'';
 const groups=[...new Set(entries.map(e=>e.post.channel))];const options=JSON.stringify(groups.map(id=>[id,current.channels.find(c=>c.id===id)?.name||id]));if(filter.dataset.options!==options){const value=filter.value;filter.replaceChildren();node('option','All groups',filter).value='';for(const id of groups)node('option',current.channels.find(c=>c.id===id)?.name||id,filter).value=id;filter.value=groups.includes(value)?value:'';filter.dataset.options=options;}
 for(const panel of $('live-feed').children)if(panel.dataset.channel)reviewBadge(panel.querySelector('h3'),panel.dataset.channel);
 for(const div of $('groups').children)reviewBadge(div.children[1],div.children[0].dataset.id);
 const list=$('review-items');if(list.contains(document.activeElement))return;
 const shown=entries.filter(e=>!filter.value||e.post.channel===filter.value),signature=JSON.stringify(shown.map(e=>[e,current.deliveries?.[e.row.id]]));if(list.dataset.signature===signature)return;list.dataset.signature=signature;list.replaceChildren();
 if(!shown.length)node('p','No pulls waiting for review.',list);
 for(const {post,row} of shown){const card=node('article','',list);node('h3',row.wellName+' / '+(current.channels.find(c=>c.id===post.channel)?.name||post.channel),card);node('p',(post.author||'Driver')+' / '+new Date(post.postedAt||post.updatedAt).toLocaleString('en-US',{timeZone:'America/Chicago'}),card);node('pre',post.body||post.chat,card);node('p',(current.deliveries?.[row.id]?.issues||row.issues||[]).join('; ')||'Held for review',card).className='warn';reviewControls(row,post,card);if(current.deliveries?.[row.id]?.needsReview)node('p',current.deliveries[row.id].correctionPending?'Correction is processing; tracking continues.':'Already sent with provisional barrels; tracking continues. Review updates this same pull.',card);else if(!canReviewPost(post,row.id))node('p','This hold needs reconciliation before it can be sent again.',card);}
}
$('review-filter').onchange=()=>renderReviews();

function renderAlertSettings(){const config=current.reviewAlerts||{},select=$('alerts-group'),signature=JSON.stringify(current.chats);if(!select.parentElement.parentElement.contains(document.activeElement)){if(select.dataset.signature!==signature){select.replaceChildren();node('option','Choose alert group',select).value='';for(const c of current.chats||[])node('option',c.name,select).value=c.id;select.dataset.signature=signature;}select.value=config.groupId||'';$('alerts-enabled').checked=!!config.enabled;}$('alerts-status').textContent=(config.enabled?'WhatsApp alerts enabled':'WhatsApp alerts off')+(config.lastSentAt?' / Last sent: '+new Date(config.lastSentAt).toLocaleString('en-US',{timeZone:'America/Chicago'}):'')+(config.error?' / Send failed: '+config.error:'');}
$('alerts-save').onclick=()=>action(()=>api('/review-alerts',JSON.stringify({enabled:$('alerts-enabled').checked,groupId:$('alerts-group').value})),$('alerts-save'),'Review alert settings saved.');

function canReviewPost(post,rowId){if(rowId&&current.deliveries?.[rowId]?.needsReview)return !post.deleted&&current.deliveries[rowId].status==='complete'&&!current.deliveries[rowId].correctionPending;return !post.deleted&&!Object.entries(current.deliveries||{}).some(([id,d])=>id.startsWith(post.key+':')&&(d.identity||['complete','duplicate','queued','incomplete'].includes(d.status)));}

function renderBarrelPolicy(force=false){
 const select=$('barrel-policy-group'),fields=$('barrel-policy-fields');
 const groups=JSON.stringify(current.channels.map(c=>[c.id,c.name]));
 if(select.dataset.groups!==groups){const old=select.value;select.replaceChildren();for(const c of current.channels)node('option',c.name,select).value=c.id;select.value=current.channels.some(c=>c.id===old)?old:(current.channels[0]?.id||'');select.dataset.groups=groups;}
 const selected=current.channels.find(c=>c.id===select.value);if(!selected)return;
 const wells=(current.wellLifecycle||[]).filter(w=>w.channels?.includes(selected.id)).map(w=>w.wellName);
 const signature=JSON.stringify([selected,wells]);if(!force&&(fields.dataset.signature===signature||fields.contains(document.activeElement)))return;
 fields.dataset.signature=signature;fields.replaceChildren();
 const label=node('label','Group / company maximum (bbls) ',fields),maximum=node('input','',label);maximum.type='number';maximum.min='1';maximum.max='1000';maximum.value=selected.options.maxLoadBbls||185;
 node('h3','Driver capacities',fields);node('p','Use the posted driver name or stable WhatsApp sender ID. Capacity is a ceiling, not the amount of every load.',fields);
 const drivers=node('div','',fields),driverInputs=[];
 function addDriver(name='',capacity=185){const row=node('div','',drivers),who=node('input','',row),amount=node('input','',row);who.value=name;who.placeholder='Driver name or sender ID';who.setAttribute('aria-label','Driver name or sender ID');amount.type='number';amount.min='1';amount.max='1000';amount.value=capacity;amount.setAttribute('aria-label','Capacity in barrels');const remove=node('button','Remove',row);remove.onclick=()=>{row.remove();driverInputs.splice(driverInputs.findIndex(e=>e.who===who),1);};driverInputs.push({who,amount});}
 for(const [name,capacity]of Object.entries(selected.options.driverCapacities||selected.options.driverDefaultBbls||{}))addDriver(name,capacity);
 const add=node('button','Add driver',fields);add.onclick=()=>addDriver();
 node('h3','Current well / job limits',fields);const wellInputs={};
 for(const name of wells){const label=node('label',name+' ',fields),amount=node('input','',label);amount.type='number';amount.min='1';amount.max='1000';amount.value=selected.options.wellLoadLimits?.[name]??'';amount.placeholder='No extra limit';amount.setAttribute('aria-label','Load limit for '+name);wellInputs[name]=amount;}
 const save=node('button','Save load limits',fields);save.onclick=()=>action(()=>api('/barrel-policy',JSON.stringify({channel:selected.id,maxLoadBbls:Number(maximum.value),driverCapacities:Object.fromEntries(driverInputs.filter(e=>e.who.value.trim()).map(e=>[e.who.value.trim(),Number(e.amount.value)])),wellLoadLimits:Object.fromEntries(Object.entries(wellInputs).filter(([,e])=>e.value!=='').map(([name,e])=>[name,Number(e.value)]))})),save,'Load limits saved locally and in Firebase.');
}
$('barrel-policy-group').onchange=()=>renderBarrelPolicy(true);
