import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {Queue,header,newestReceiverMessages} from './core.mjs';
test('durable deduplication, edits, deletion and multiple wells',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-watchdog-'));try{let q=new Queue(dir);const event={id:'message-1',channel:'group-1',chat:header('2026-10-03T01:00:00Z','driver','Kahuna 5\nTop 12.5\nBottom 11.1\n165 bbl')};assert.equal(q.ingest(event).rows,1);q=new Queue(dir);assert.equal(q.ingest(event).duplicate,true);assert.equal(q.snapshot().pullCount,1);q.ingest({...event,chat:event.chat.replace('12.5','12.6')});assert.equal(q.snapshot().messages[0].edited,true);assert.equal(q.snapshot().messages[0].rows[0].tankLevelFeet,12.6);q.ingest({...event,deleted:true});assert.equal(q.snapshot().pullCount,0);assert.equal(q.export('group-1'),'');q.ingest({...event,id:'message-2',chat:header('2026-10-03T01:00:00Z','driver','Gunslinger 3\nTop 14\nBottom 12\nGunslinger 5\nTop 13\nBottom 11\n165 bbl')});assert.equal(q.snapshot().pullCount,2);assert.ok(q.snapshot().messages[0].rows.some(r=>r.issues.length));}finally{rmSync(dir,{recursive:true,force:true});}});

import {Transport,signedRequest} from './transport.mjs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {verifyHmacHeaders}=require('../../functions/lib/watchdog/auth.js');
test('signed client requests are bound to endpoint and exact body',()=>{process.env.WATCHDOG_HMAC_KEY_V1='synthetic-test-key';const request=signedRequest('ingestWatchdogPullV2',{chat:'synthetic'},'synthetic-test-key');assert.equal(verifyHmacHeaders({endpointName:'ingestWatchdogPullV2',method:'POST',headers:request.headers,rawBody:request.body}).ok,true);assert.equal(verifyHmacHeaders({endpointName:'getWatchdogPullReceiptV2',method:'POST',headers:request.headers,rawBody:request.body}).ok,false);});
test('durable transport sends live rows once and never sends replay samples',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-transport-'));try{const queue=new Queue(dir);const chat=header(Date.now(),'Driver','Kahuna 5\nTop 12.5\nBottom 11.125\n165 bbl');queue.ingest({id:'live-message',channel:'group',chat});queue.ingest({id:'export:sample',channel:'sample',chat});const t=new Transport(queue);t.lastLifecycleCheck=Date.now();t.secret='synthetic';t.config={enabled:true,enabledAt:Date.now()-60000};let calls=0;t.request=async endpoint=>{calls++;return endpoint==='ingestWatchdogPullV2'?{ok:true,status:'queued',identity:'synthetic-id'}:{ok:true,status:'complete',identity:'synthetic-id'};};await t.tick(false);assert.equal(calls,2);await t.tick(false);assert.equal(calls,2);assert.equal(Object.values(new Queue(dir).data.deliveries)[0].status,'complete');}finally{rmSync(dir,{recursive:true,force:true});}});

test('live feed includes ordinary chat posts only from watched groups and excludes replay',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-feed-'));try{const queue=new Queue(dir);queue.ingest({id:'live-1',channel:'watched',chat:header('2026-10-03T02:00:00Z','Danny','Heading to the pad')});queue.ingest({id:'live-2',channel:'other',chat:header('2026-10-03T03:00:00Z','Other','Hello')});queue.ingest({id:'export:sample',channel:'watched',chat:header('2026-10-03T04:00:00Z','Sample','Old export')});assert.equal(queue.liveFeed(['watched']).length,1);assert.equal(queue.liveFeed(['watched'])[0].body,'Heading to the pad');assert.equal(queue.liveFeed(['watched'])[0].postedAt,'2026-10-03T02:00:00.000Z');assert.equal(queue.liveFeed(['watched'])[0].author,'Danny');}finally{rmSync(dir,{recursive:true,force:true});}});

test('busy group cannot crowd another watched group out of the live feed',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-fair-feed-'));try{const q=new Queue(dir);q.ingest({id:'quiet',channel:'quiet',chat:header('2026-10-03T01:00:00Z','Driver','Quiet post')});for(let i=0;i<110;i++)q.ingest({id:'busy-'+i,channel:'busy',chat:header(Date.parse('2026-10-03T02:00:00Z')+i*1000,'Driver','Busy post')});const posts=q.liveFeed(['quiet','busy']);assert.equal(posts.filter(p=>p.channel==='busy').length,100);assert.equal(posts.filter(p=>p.channel==='quiet').length,1);}finally{rmSync(dir,{recursive:true,force:true});}});

test('receiver deduplicates before selecting newest posts per group',()=>{const old=Array.from({length:100},(_,i)=>({id:'old'+i,channel:'busy',timestamp:i}));const fresh={id:'new',channel:'busy',timestamp:1000};const quiet={id:'quiet',channel:'quiet',timestamp:0};const result=newestReceiverMessages([...old,fresh,...old,...old,quiet]);assert.equal(result.length,101);assert.equal(result[0].id,'new');assert.equal(result.filter(m=>m.id==='old99').length,1);assert.ok(result.some(m=>m.id==='quiet'));assert.ok(!result.some(m=>m.id==='old0'));});

test('transport accepts a top and barrels without a reported bottom',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-no-bottom-'));try{const q=new Queue(dir);q.ingest({id:'fresh',channel:'group',chat:header(Date.now(),'Driver','Kahuna 5\nTop 12.5\n165 bbl')});const t=new Transport(q);t.lastLifecycleCheck=Date.now();t.secret='synthetic';t.config={enabled:true,enabledAt:Date.now()-60000};let calls=0;t.request=async endpoint=>{calls++;return endpoint==='ingestWatchdogPullV2'?{ok:true,status:'queued',identity:'test'}:{ok:true,status:'complete',identity:'test'};};await t.tick(false);assert.equal(calls,2);}finally{rmSync(dir,{recursive:true,force:true});}});

test('sender display metadata changes do not mark the same post edited',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-author-'));try{const q=new Queue(dir);const event={id:'same',channel:'g',chat:header('2026-10-03T12:57:12Z','Driver name','Cyclone 2\nTop 11.7\n185 bbl')};q.ingest(event);q.ingest({...event,chat:event.chat.replace('Driver name','156440023019675@lid')});assert.equal(q.snapshot().messages[0].edited,false);q.ingest({...event,chat:event.chat.replace('11.7','11.8')});assert.equal(q.snapshot().messages[0].edited,true);}finally{rmSync(dir,{recursive:true,force:true});}});
test('review corrects measurement time with original observation preserved and exclusion is durable',async()=>{
 const dir=mkdtempSync(path.join(os.tmpdir(),'wb-review-'));try{
  const q=new Queue(dir);q.ingest({id:'live-review',channel:'group',chat:header(Date.now(),'Driver','Kahuna 5\nTop 12.5\n165 bbl')});const row=Object.values(q.data.messages)[0].rows[0];q.data.deliveries={[row.id]:{status:'review',issues:['Possible existing pull within 30 minutes']}};
  const t=new Transport(q);t.lastLifecycleCheck=Date.now();t.secret='synthetic';t.config={enabled:true,enabledAt:0};let sent;t.request=async(_endpoint,body)=>{sent=body;return {ok:true,status:'queued',identity:'reviewed'};};
  const corrected=new Date(Date.now()-60000).toISOString();await t.review(row.id,'confirm',corrected,'Driver confirmed time');assert.equal(sent.review.dateTimeUTC,corrected);assert.equal(sent.chat,Object.values(q.data.messages)[0].chat);assert.equal(new Queue(dir).data.deliveries[row.id].review.reason,'Driver confirmed time');
  await assert.rejects(()=>t.review(row.id,'exclude',null,'Not a load'));
  q.data.deliveries[row.id]={status:'review'};await t.review(row.id,'exclude',null,'Duplicate chat post');assert.equal(new Queue(dir).data.deliveries[row.id].status,'excluded');let calls=0;t.request=async()=>{calls++;};await t.tick(false);assert.equal(calls,0);
 }finally{rmSync(dir,{recursive:true,force:true});}
});

test('group barrel fallback is configurable and written barrels take precedence',()=>{
 const dir=mkdtempSync(path.join(os.tmpdir(),'wb-variable-barrels-'));
 try { const q=new Queue(dir);
 q.ingest({id:'missing',channel:'group',chat:header(Date.now(),'Driver','Gunslinger 3\nTop 12\nBottom 10'),options:{defaultBbls:140}});
 q.ingest({id:'written',channel:'group',chat:header(Date.now(),'Driver','Gunslinger 3\nTop 12\nBottom 10\n185 bbl'),options:{defaultBbls:140}});
 const rows=q.snapshot().messages.flatMap(m=>m.rows);
 assert.deepEqual(rows.map(r=>r.bblsTaken).sort((a,b)=>a-b),[140,185]);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
