import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {Queue,header} from './core.mjs';
test('durable deduplication, edits, deletion and multiple wells',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-watchdog-'));try{let q=new Queue(dir);const event={id:'message-1',channel:'group-1',chat:header('2026-10-03T01:00:00Z','driver','Kahuna 5\nTop 12.5\nBottom 11.1\n165 bbl')};assert.equal(q.ingest(event).rows,1);q=new Queue(dir);assert.equal(q.ingest(event).duplicate,true);assert.equal(q.snapshot().pullCount,1);q.ingest({...event,chat:event.chat.replace('12.5','12.6')});assert.equal(q.snapshot().messages[0].edited,true);assert.equal(q.snapshot().messages[0].rows[0].tankLevelFeet,12.6);q.ingest({...event,deleted:true});assert.equal(q.snapshot().pullCount,0);assert.equal(q.export('group-1'),'');q.ingest({...event,id:'message-2',chat:header('2026-10-03T01:00:00Z','driver','Gunslinger 3\nTop 14\nBottom 12\nGunslinger 5\nTop 13\nBottom 11\n165 bbl')});assert.equal(q.snapshot().pullCount,2);assert.ok(q.snapshot().messages[0].rows.some(r=>r.issues.length));}finally{rmSync(dir,{recursive:true,force:true});}});

import {Transport,signedRequest} from './transport.mjs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {verifyHmacHeaders}=require('../../functions/lib/watchdog/auth.js');
test('signed client requests are bound to endpoint and exact body',()=>{process.env.WATCHDOG_HMAC_KEY_V1='synthetic-test-key';const request=signedRequest('ingestWatchdogPullV2',{chat:'synthetic'},'synthetic-test-key');assert.equal(verifyHmacHeaders({endpointName:'ingestWatchdogPullV2',method:'POST',headers:request.headers,rawBody:request.body}).ok,true);assert.equal(verifyHmacHeaders({endpointName:'getWatchdogPullReceiptV2',method:'POST',headers:request.headers,rawBody:request.body}).ok,false);});
test('durable transport sends live rows once and never sends replay samples',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'wb-transport-'));try{const queue=new Queue(dir);const chat=header(Date.now(),'Driver','Kahuna 5\nTop 12.5\nBottom 11.125\n165 bbl');queue.ingest({id:'live-message',channel:'group',chat});queue.ingest({id:'export:sample',channel:'sample',chat});const t=new Transport(queue);t.secret='synthetic';t.config={enabled:true,enabledAt:Date.now()-60000};let calls=0;t.request=async endpoint=>{calls++;return endpoint==='ingestWatchdogPullV2'?{ok:true,status:'queued',identity:'synthetic-id'}:{ok:true,status:'complete',identity:'synthetic-id'};};await t.tick(false);assert.equal(calls,2);await t.tick(false);assert.equal(calls,2);assert.equal(Object.values(new Queue(dir).data.deliveries)[0].status,'complete');}finally{rmSync(dir,{recursive:true,force:true});}});
