import {createHash,createHmac,randomBytes} from 'node:crypto';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
const origin='https://us-central1-wellbuilt-sync.cloudfunctions.net/';
export function signedRequest(endpoint,body,secret){const raw=JSON.stringify(body),timestamp=String(Date.now()),nonce=randomBytes(16).toString('hex');const digest=createHash('sha256').update(raw).digest('hex');return {method:'POST',headers:{'Content-Type':'application/json','x-watchdog-key-id':'V1','x-watchdog-timestamp':timestamp,'x-watchdog-nonce':nonce,'x-watchdog-signature':createHmac('sha256',secret).update(`v1:${endpoint}:POST:${timestamp}:${nonce}:${digest}`).digest('hex')},body:raw,signal:AbortSignal.timeout(20000)};}
export class Transport{
 constructor(queue){this.queue=queue;this.channelOptions={};this.busy=false;this.secret=null;this.status='Not configured';}
 configure(){const file=path.join(this.queue.directory,'transport.json');try{this.config=JSON.parse(readFileSync(file,'utf8'));if(!this.config.enabled){this.status='Disabled';return;}const protectedFile=path.join(this.queue.directory,'hmac-key.dpapi');const script="$s=(Get-Content -LiteralPath $env:WBC_KEY_FILE -Raw).Trim() | ConvertTo-SecureString; $p=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($s);try{[Console]::Write([Runtime.InteropServices.Marshal]::PtrToStringBSTR($p))}finally{[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($p)}";this.secret=execFileSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{encoding:'utf8',windowsHide:true,env:{...process.env,PSModulePath:process.env.SystemRoot+'\\System32\\WindowsPowerShell\\v1.0\\Modules',WBC_KEY_FILE:protectedFile},stdio:['ignore','pipe','pipe']});if(this.secret.length<16)throw Error('Credential unavailable');this.status='Ready';}catch{this.status='Not configured';}}
 async request(endpoint,body){const response=await fetch(origin+endpoint,signedRequest(endpoint,body,this.secret));const result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'Intake request failed');return result;}
 async lifecycle(){const result=await this.request('getWatchdogWellLifecycleV2',{});this.wells=result.wells;return result;}
 async stopWell(wellName,reason){if(this.busy)throw Error('Delivery in progress; try again');this.busy=true;try{const result=await this.request('stopWatchdogWellV2',{wellName,reason});await this.lifecycle();return result;}finally{this.busy=false;}}
 async review(rowId,decision,dateTimeUTC,reason){
  if(this.busy)throw Error('Delivery in progress; try again in a moment');
  const message=Object.values(this.queue.data.messages).find(m=>m.rows.some(r=>r.id===rowId));
  const index=message?.rows.findIndex(r=>r.id===rowId),row=message?.rows[index];
  const previous=this.queue.data.deliveries?.[rowId];
  if(!row||message.deleted||message.edited||previous?.status!=='review'||previous.identity)throw Error('This entry is not available for review');
  if(decision==='exclude'){this.queue.data.deliveries[rowId]={...previous,status:'excluded',review:{reason,at:new Date().toISOString()}};this.queue.save();return;}
  if(decision!=='confirm'||!this.secret||!this.config?.enabled)throw Error('Transport unavailable');
  this.busy=true;try{
   const delivery=await this.request('ingestWatchdogPullV2',{chatId:message.channel,messageId:message.id,chat:message.chat,rowIndex:index,defaultBbls:this.channelOptions[message.channel]?.defaultBbls??null,review:{confirmed:true,dateTimeUTC,reason}});
   this.queue.data.deliveries[rowId]={...delivery,review:{dateTimeUTC,reason,at:new Date().toISOString()}};this.queue.save();
  }finally{this.busy=false;}
 }
 async tick(paused){if(paused||this.busy||!this.secret||!this.config?.enabled)return;this.busy=true;try{if(!this.lastLifecycleCheck||Date.now()-this.lastLifecycleCheck>60000){await this.lifecycle();this.lastLifecycleCheck=Date.now();}this.queue.reparseChannels(Object.fromEntries(Object.entries(this.channelOptions).map(([id,options])=>[id,{...options,wellNames:(this.wells||[]).filter(w=>w.channels?.includes(id)).map(w=>w.wellName)}])));let sent=0;for(const message of Object.values(this.queue.data.messages)){if(message.deleted||message.edited||message.id.startsWith('export:'))continue;for(let index=0;index<message.rows.length;index++){const row=message.rows[index];if(Date.parse(row.postedAt)<this.config.enabledAt||Date.parse(row.dateTimeUTC)<this.config.enabledAt)continue;if(this.wells?.some(w=>w.wellName===row.wellName&&w.archive))continue;const key=row.id;this.queue.data.deliveries??={};let delivery=this.queue.data.deliveries[key];if(delivery&&['complete','duplicate','review','excluded','archived','before_activation'].includes(delivery.status))continue;if(row.issues.length||message.notices.length){this.queue.data.deliveries[key]={status:'review',issues:row.issues.length?row.issues:['Tank setup needs review']};this.queue.save();continue;}if(!delivery?.identity){delivery=await this.request('ingestWatchdogPullV2',{chatId:message.channel,messageId:message.id,chat:message.chat,rowIndex:index,defaultBbls:this.channelOptions[message.channel]?.defaultBbls??null});this.queue.data.deliveries[key]=delivery;this.queue.save();}if(delivery.identity){const receipt=await this.request('getWatchdogPullReceiptV2',{identity:delivery.identity});this.queue.data.deliveries[key]=receipt;this.queue.save();}if(++sent>=10)break;}if(sent>=10)break;}this.status='Ready';}catch(e){this.status='Retry pending: '+e.message;}finally{this.busy=false;}}
}
