// Cross-repo contract fixture — SERVER side (Thor 1 requirement 2). Consumes the
// golden fixture generated by the REAL WB-M builders (client repo test
// governedContractFixture) VERBATIM through the real candidate ingest→processing
// pipeline. Recomputes the digest and fails loudly on client/server drift. No
// packet shape is hand-retyped here — every packet comes from the golden file.
//
// RUN: node functions/emulator/run.mjs contractfixture
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const HERE = dirname(fileURLToPath(import.meta.url));
const GOLDEN = join(HERE, 'fixtures', 'wbm-governed-contract.json');

const PROJECT_ID = process.env.GCLOUD_PROJECT || 'wellbuilt-sync';
process.env.FIREBASE_CONFIG = JSON.stringify({ projectId: PROJECT_ID, databaseURL: `http://${process.env.FIREBASE_DATABASE_EMULATOR_HOST || '127.0.0.1:9002'}/?ns=${PROJECT_ID}-default-rtdb` });
const adminMod = await import('firebase-admin');
const admin = adminMod.default ?? adminMod;
admin.initializeApp();
const db = admin.database();
const AUTH_HOST = process.env.FIREBASE_AUTH_EMULATOR_HOST || '127.0.0.1:9199';
const FN = (n) => `http://127.0.0.1:5003/${PROJECT_ID}/us-central1/${n}`;

let failures = 0; const results = [];
const check = (n, c, d = '') => { if (c) results.push(`  PASS  ${n}`); else { failures++; results.push(`  FAIL  ${n}  ${d}`); } };
const val = async (p) => (await db.ref(p).once('value')).val();
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const WELL = 'Thor 1', DRIVER_ID = 'emu-driver-fx', PID = '20260830_123821_Thor1_unozct';

const golden = JSON.parse(readFileSync(GOLDEN, 'utf8'));
const fx = golden.fixtures;

async function tokenFor() {
  const uid = `driver_${DRIVER_ID}`;
  await admin.auth().createUser({ uid }).catch(() => {});
  await admin.auth().setCustomUserClaims(uid, { kind: 'driver', driverId: DRIVER_ID, companyId: 'liquid-gold', roles: ['driver'] });
  const custom = await admin.auth().createCustomToken(uid);
  const j = await (await fetch(`http://${AUTH_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=fake`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ token: custom, returnSecureToken: true }) })).json();
  return j.idToken;
}
const call = async (fn, packet, tok) => { const r = await fetch(FN(fn), { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${tok}` }, body: JSON.stringify({ data: { packet } }) }); return { status: r.status, body: await r.json().catch(() => ({})) }; };
const isDown = async () => val(`wells/${WELL}/status/isDown`);
async function waitDown(want, ms = 14000) { const s = Date.now(); while (Date.now() - s < ms) { if ((await isDown()) === want) return true; await sleep(300); } return false; }

async function seed() {
  await db.ref('/').set(null);
  await db.ref(`well_config/${WELL}`).set({ tanks: 1, bblPerFoot: 20, bottomLevel: 3, pullBbls: 140, route: 'Thors', companyId: 'liquid-gold' });
  await db.ref(`drivers/profiles/${DRIVER_ID}`).set({ active: true, companyId: 'liquid-gold', displayName: 'FX', assignedRoutes: ['Thors'], assignedWells: [] });
  await admin.firestore().collection('driver_credentials').doc(DRIVER_ID).set({ active: true });
  await db.ref('packets/incoming_version').set(9000);
  for (let i = 6; i >= 1; i--) { const day = 24 + (6 - i); const hid = `202608${day}_120000_Thor1_hist0${i}`; await db.ref(`packets/processed/${hid}`).set({ packetId: hid, wellName: WELL, companyId: 'liquid-gold', driverId: DRIVER_ID, dateTimeUTC: `2026-08-${day}T17:00:00.000Z`, dateTime: `8/${day} 12PM`, bblsTaken: 140, tankTopInches: 136, tankLevelFeet: 136 / 12, tankAfterInches: 52 + i, wellDown: false, processedAt: new Date().toISOString() }); }
  // The Thor original pull (edited by the edit fixtures), currently DOWN.
  await db.ref(`packets/processed/${PID}`).set({ packetId: PID, wellName: WELL, companyId: 'liquid-gold', driverId: DRIVER_ID, dateTimeUTC: '2026-08-30T17:38:09.654Z', dateTime: '8/30 12:38PM', bblsTaken: 140, tankTopInches: 136, tankLevelFeet: 136 / 12, tankAfterInches: 52, wellDown: true, processedAt: new Date().toISOString() });
  await db.ref(`packets/outgoing/response_seed_${PID}`).set({ wellName: WELL, lastPullPacketId: PID, lastPullDateTimeUTC: '2026-08-30T17:38:09.654Z', wellDown: true, isEdit: false });
  await db.ref(`wells/${WELL}/status`).set({ wellName: WELL, isDown: true, updatedAt: new Date().toISOString(), current: { levelInches: 52 }, lastPull: { packetId: PID, dateTimeUTC: '2026-08-30T17:38:09.654Z', bblsTaken: 140 } });
}

async function main() {
  // ── DRIFT TRIPWIRE: the server's golden digest must equal the stored digest. ──
  const recomputed = createHash('sha256').update(JSON.stringify(fx)).digest('hex');
  check('golden fixture digest matches (client↔server contract not drifted)', recomputed === golden.digest, `${recomputed.slice(0, 16)} vs ${golden.digest.slice(0, 16)}`);
  check('golden fixture version present + 7 scenarios', golden.version >= 1 && ['createFalse', 'createTrue', 'editFalse', 'editTrue', 'editRetry', 'editSecond', 'editOmitted'].every((k) => fx[k]));

  const tok = await tokenFor();
  check('driver token issued', !!tok);

  // ── CREATE fixtures through the REAL ingestWbmPull → processIncomingPull ──
  await seed();
  const cf = await call('ingestWbmPull', fx.createFalse, tok);
  check('fixture createFalse accepted', cf.status === 200 && cf.body?.result?.ok === true, JSON.stringify(cf.body));
  check('fixture createFalse (explicit false) CLEARS a DOWN well → Running', await waitDown(false));
  const ct = await call('ingestWbmPull', fx.createTrue, tok);
  check('fixture createTrue accepted', ct.status === 200 && ct.body?.result?.ok === true);
  check('fixture createTrue (explicit true, newest) MARKS DOWN', await waitDown(true));

  // ── EDIT fixtures through the REAL ingestWbmEdit → processEditRequest ──
  await seed();
  const ef = await call('ingestWbmEdit', fx.editFalse, tok);
  check('fixture editFalse accepted', ef.status === 200 && ef.body?.result?.ok === true, JSON.stringify(ef.body));
  check('fixture editFalse (wellDown false in mask) → Running everywhere', await waitDown(false) && (await val(`packets/processed/${PID}`))?.wellDown === false);

  await seed();
  const et = await call('ingestWbmEdit', fx.editTrue, tok);
  check('fixture editTrue accepted', et.status === 200 && et.body?.result?.ok === true);
  check('fixture editTrue (wellDown true in mask) → DOWN', await waitDown(true));

  // Retry: same editEventId + material → idempotent (single application).
  await seed();
  await call('ingestWbmEdit', fx.editFalse, tok); await waitDown(false);
  // Let the first edit's atomic commit fully settle (no coordinator lock) before
  // the retry, so this asserts idempotency — not a concurrent-mutation race.
  { const s = Date.now(); while (Date.now() - s < 8000) { const w = (await val('wells')) || {}; if (!Object.values(w).some((x) => x?.status?.chronoLock)) break; await sleep(200); } await sleep(1500); }
  await call('ingestWbmEdit', fx.editRetry, tok);
  // Wait for the retry to fully settle (no coordinator lock) and a STABLE
  // Running state across two reads — the idempotent end state, not a mid-flight one.
  let stableRunning = false;
  { const s = Date.now(); while (Date.now() - s < 15000) { const w = (await val('wells')) || {}; const lock = Object.values(w).some((x) => x?.status?.chronoLock); if (!lock && (await isDown()) === false) { await sleep(1200); if ((await isDown()) === false) { stableRunning = true; break; } } await sleep(300); } }
  check('fixture editRetry (identical editEventId) is idempotent — settles STABLE Running', stableRunning && (await val(`packets/processed/${PID}`))?.wellDown === false, JSON.stringify({ isDown: await isDown() }));

  // API-style edit with wellDown OMITTED from the mask → preserves prior status.
  await seed(); // DOWN
  const eo = await call('ingestWbmEdit', fx.editOmitted, tok);
  check('fixture editOmitted accepted', eo.status === 200 && eo.body?.result?.ok === true, JSON.stringify(eo.body));
  await sleep(4000);
  check('fixture editOmitted (wellDown NOT in mask) PRESERVES prior DOWN', (await isDown()) === true);

  console.log('\n=== GOVERNED CONTRACT FIXTURE (real builders → real ingest/processing) ===');
  console.log(results.join('\n'));
  console.log(`\n${failures === 0 ? 'ALL PASS' : failures + ' FAILURES'} (${results.length} checks)`);
  process.exit(failures === 0 ? 0 : 1);
}
main().catch((e) => { console.error('[contractFixture] fatal', e); process.exit(2); });
