'use client';

import { useState, useRef } from 'react';
import {
  type CompanyConfig,
  updateCompanyFields,
  extractColorPalette,
  uploadCompanyLogo,
  uploadCompanyThermalLogo,
  generateThermalLogo,
} from '@/lib/companySettings';

interface Props {
  company: CompanyConfig;
  onSave: () => void;
}

export function BrandingCard({ company, onSave }: Props) {
  const [showModal, setShowModal] = useState(false);
  const [logoFile, setLogoFile] = useState<File | null>(null);
  const [logoPreview, setLogoPreview] = useState<string | null>(null);
  const [thermalFile, setThermalFile] = useState<File | Blob | null>(null);
  const [thermalPreview, setThermalPreview] = useState<string | null>(null);
  const [thermalAutoGenerated, setThermalAutoGenerated] = useState(false);
  const [extractedPalette, setExtractedPalette] = useState<string[]>([]);
  const [manualColor, setManualColor] = useState('');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const logoInputRef = useRef<HTMLInputElement>(null);
  const thermalInputRef = useRef<HTMLInputElement>(null);

  const openEditor = () => {
    setLogoFile(null);
    setLogoPreview(company.logoUrl || null);
    setThermalFile(null);
    setThermalPreview(company.thermalLogoUrl || null);
    setThermalAutoGenerated(false);
    setManualColor(company.primaryColor || '');
    setError('');

    if (company.logoUrl) {
      extractColorPalette(company.logoUrl)
        .then(palette => setExtractedPalette(palette))
        .catch(() => setExtractedPalette([]));
    } else {
      setExtractedPalette([]);
    }

    setShowModal(true);
  };

  const autoGenerateThermal = async (imageUrl: string) => {
    try {
      const blob = await generateThermalLogo(imageUrl);
      setThermalFile(blob);
      setThermalPreview(URL.createObjectURL(blob));
      setThermalAutoGenerated(true);
    } catch (err) {
      console.warn('Auto thermal conversion failed:', err);
    }
  };

  const handleLogoSelect = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!['image/png', 'image/jpeg', 'image/jpg'].includes(file.type)) {
      setError('Logo must be PNG or JPG');
      return;
    }

    if (file.size > 500 * 1024) {
      setError('Logo must be under 500KB');
      return;
    }

    setError('');
    setLogoFile(file);
    const previewUrl = URL.createObjectURL(file);
    setLogoPreview(previewUrl);

    try {
      const palette = await extractColorPalette(previewUrl);
      setExtractedPalette(palette);
      setManualColor(palette[0] || manualColor);
    } catch {
      setExtractedPalette([]);
    }

    // Auto-generate thermal version (can be overridden by manual upload)
    autoGenerateThermal(previewUrl);
  };

  const handleThermalSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!['image/png', 'image/jpeg', 'image/jpg'].includes(file.type)) {
      setError('Thermal logo must be PNG or JPG');
      return;
    }

    if (file.size > 500 * 1024) {
      setError('Thermal logo must be under 500KB');
      return;
    }

    setError('');
    setThermalFile(file);
    setThermalPreview(URL.createObjectURL(file));
    setThermalAutoGenerated(false);
  };

  const save = async () => {
    setSaving(true);
    setError('');
    let hasUploadError = false;
    const errors: string[] = [];
    try {
      const updates: Record<string, any> = {};

      if (logoFile) {
        try {
          const logoUrl = await uploadCompanyLogo(company.id, logoFile);
          updates.logoUrl = logoUrl;
        } catch (err: any) {
          errors.push(`Color logo: ${err.message?.slice(0, 500)}`);
          hasUploadError = true;
        }
      }

      if (thermalFile) {
        try {
          const thermalUrl = await uploadCompanyThermalLogo(company.id, thermalFile);
          updates.thermalLogoUrl = thermalUrl;
        } catch (err: any) {
          errors.push(`Thermal logo: ${err.message?.slice(0, 500)}`);
          hasUploadError = true;
        }
      }

      if (errors.length > 0) setError(errors.join(' | '));

      const color = manualColor.trim();
      if (color && /^#[0-9A-Fa-f]{6}$/.test(color)) {
        updates.primaryColor = color.toUpperCase();
      }

      // Save whatever succeeded, but keep modal open if any upload failed
      if (Object.keys(updates).length > 0) {
        await updateCompanyFields(company.id, updates);
        if (!hasUploadError) {
          setShowModal(false);
        }
        onSave();
      } else if (!error) {
        setError('No changes to save');
      }
    } catch (err) {
      console.error('Failed to save branding:', err);
      setError('Failed to save branding');
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <div className="bg-gray-800 rounded-lg overflow-hidden">
        <div className="flex items-center justify-between px-4 py-3 border-b border-purple-500/30 bg-purple-900/20">
          <h3 className="text-purple-400 font-medium text-sm">Branding</h3>
          <button
            onClick={openEditor}
            className="px-3 py-1 text-xs rounded bg-purple-600 hover:bg-purple-500 text-white"
          >
            {company.logoUrl || company.primaryColor ? 'Edit' : '+ Set Up'}
          </button>
        </div>

        <div className="p-4">
          <div className="flex items-center gap-4 text-sm">
            {company.logoUrl ? (
              <div className="flex flex-col items-center gap-1">
                <img
                  src={company.logoUrl}
                  alt={`${company.name} logo`}
                  className="h-10 w-auto rounded bg-white/10 p-1"
                />
                <span className="text-gray-500 text-[10px]">Color</span>
              </div>
            ) : (
              <span className="text-gray-500 text-xs">No logo uploaded</span>
            )}
            {company.thermalLogoUrl && (
              <div className="flex flex-col items-center gap-1">
                <img
                  src={company.thermalLogoUrl}
                  alt={`${company.name} thermal logo`}
                  className="h-10 w-auto rounded bg-white p-1"
                />
                <span className="text-gray-500 text-[10px]">Thermal</span>
              </div>
            )}
            {company.primaryColor ? (
              <div className="flex items-center gap-2">
                <div
                  className="w-6 h-6 rounded border border-gray-500"
                  style={{ backgroundColor: company.primaryColor }}
                />
                <span className="text-gray-300 font-mono text-xs">{company.primaryColor}</span>
              </div>
            ) : (
              <span className="text-gray-500 text-xs">Default gold (#FFD700)</span>
            )}
          </div>
        </div>
      </div>

      {/* Branding Editor Modal */}
      {showModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-gray-800 rounded-lg p-6 max-w-lg w-full mx-4 max-h-[90vh] overflow-y-auto">
            <h3 className="text-white font-medium mb-1">Company Branding</h3>
            <p className="text-gray-400 text-xs mb-4">
              Upload logos and set your accent color. Drivers will see this on their tickets and invoices.
            </p>

            {error && (
              <div className="p-2 mb-3 bg-red-900/50 text-red-300 text-xs rounded">{error}</div>
            )}

            {/* Color Logo Upload */}
            <div className="mb-4">
              <label className="text-gray-400 text-sm block mb-2">Color Logo</label>
              <p className="text-gray-500 text-xs mb-2">Shown on digital invoices, dashboard, and app screens.</p>
              <div className="flex items-center gap-4">
                {logoPreview ? (
                  <div className="relative">
                    <img
                      src={logoPreview}
                      alt="Logo preview"
                      className="h-16 w-auto rounded bg-white/10 p-1"
                    />
                    <button
                      onClick={() => { setLogoFile(null); setLogoPreview(null); setExtractedPalette([]); }}
                      className="absolute -top-1 -right-1 bg-red-600 text-white rounded-full w-4 h-4 text-xs flex items-center justify-center"
                    >
                      x
                    </button>
                  </div>
                ) : (
                  <div className="h-16 w-16 rounded border-2 border-dashed border-gray-600 flex items-center justify-center">
                    <span className="text-gray-500 text-2xl">+</span>
                  </div>
                )}
                <div>
                  <button
                    onClick={() => logoInputRef.current?.click()}
                    className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded"
                  >
                    {logoPreview ? 'Change' : 'Upload'}
                  </button>
                  <p className="text-gray-500 text-xs mt-1">PNG or JPG, max 500KB</p>
                </div>
                <input
                  ref={logoInputRef}
                  type="file"
                  accept="image/png,image/jpeg"
                  onChange={handleLogoSelect}
                  className="hidden"
                />
              </div>
            </div>

            {/* Thermal Print Logo */}
            <div className="mb-4">
              <label className="text-gray-400 text-sm block mb-2">Thermal Print Logo</label>
              <p className="text-gray-500 text-xs mb-2">
                Black & white version for thermal receipt printers. Auto-generated from color logo, or upload your own.
              </p>
              <div className="flex items-center gap-4">
                {thermalPreview ? (
                  <div className="relative">
                    <img
                      src={thermalPreview}
                      alt="Thermal logo preview"
                      className="h-16 w-auto rounded bg-white p-1"
                    />
                    {thermalAutoGenerated && (
                      <span className="absolute -bottom-1 left-0 right-0 text-center text-[9px] text-yellow-400">auto</span>
                    )}
                    <button
                      onClick={() => { setThermalFile(null); setThermalPreview(null); setThermalAutoGenerated(false); }}
                      className="absolute -top-1 -right-1 bg-red-600 text-white rounded-full w-4 h-4 text-xs flex items-center justify-center"
                    >
                      x
                    </button>
                  </div>
                ) : (
                  <div className="h-16 w-16 rounded border-2 border-dashed border-gray-600 flex items-center justify-center bg-white/5">
                    <span className="text-gray-500 text-2xl">+</span>
                  </div>
                )}
                <div className="flex flex-col gap-1">
                  <button
                    onClick={() => thermalInputRef.current?.click()}
                    className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 text-white text-sm rounded"
                  >
                    {thermalPreview ? 'Replace' : 'Upload Custom'}
                  </button>
                  {logoPreview && !thermalAutoGenerated && (
                    <button
                      onClick={() => autoGenerateThermal(logoPreview)}
                      className="px-3 py-1 bg-gray-700/50 hover:bg-gray-600/50 text-gray-300 text-xs rounded"
                    >
                      Auto-generate from color logo
                    </button>
                  )}
                </div>
                <input
                  ref={thermalInputRef}
                  type="file"
                  accept="image/png,image/jpeg"
                  onChange={handleThermalSelect}
                  className="hidden"
                />
              </div>
              {thermalAutoGenerated && (
                <p className="text-yellow-400/70 text-xs mt-2">
                  Auto-generated. If it doesn't look right, upload a custom B&W version.
                </p>
              )}
            </div>

            {/* Color Section */}
            <div className="mb-4">
              <label className="text-gray-400 text-sm block mb-2">Accent Color</label>

              {extractedPalette.length > 0 && (
                <div className="mb-3">
                  <div className="text-gray-500 text-xs mb-1.5">Colors from your logo — click to select:</div>
                  <div className="flex gap-2">
                    {extractedPalette.map((color, i) => (
                      <button
                        key={i}
                        onClick={() => setManualColor(color)}
                        className="relative group"
                        title={color}
                      >
                        <div
                          className="w-10 h-10 rounded-lg border-2 transition-all"
                          style={{
                            backgroundColor: color,
                            borderColor: manualColor === color ? '#FFFFFF' : 'transparent',
                            boxShadow: manualColor === color ? '0 0 0 2px rgba(255,255,255,0.3)' : 'none',
                          }}
                        />
                        {manualColor === color && (
                          <div className="absolute -bottom-1 left-1/2 -translate-x-1/2 w-1.5 h-1.5 bg-white rounded-full" />
                        )}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <div className="flex items-center gap-3">
                <input
                  type="color"
                  value={manualColor || '#FFD700'}
                  onChange={e => setManualColor(e.target.value.toUpperCase())}
                  className="w-8 h-8 rounded cursor-pointer bg-transparent border-0"
                  title="Custom color picker"
                />
                <input
                  type="text"
                  value={manualColor}
                  onChange={e => setManualColor(e.target.value.toUpperCase())}
                  placeholder="#FFD700"
                  maxLength={7}
                  className="px-3 py-2 bg-gray-700 text-white rounded text-sm font-mono w-28"
                />
                <span className="text-gray-500 text-xs">or pick custom</span>
              </div>
            </div>

            {/* Preview Strip */}
            {manualColor && /^#[0-9A-Fa-f]{6}$/.test(manualColor) && (
              <div
                className="mb-4 p-3 rounded-lg border"
                style={{ borderColor: manualColor, backgroundColor: '#1a1a0a' }}
              >
                <div className="flex items-center gap-2 justify-center mb-1">
                  <span style={{ color: manualColor }} className="text-sm font-bold tracking-widest">EN ROUTE</span>
                </div>
                <div className="text-white text-center text-sm font-semibold">Sample Well Name</div>
                <div className="flex justify-center mt-2">
                  <div
                    className="px-6 py-2 rounded-lg text-sm font-bold text-black"
                    style={{ backgroundColor: manualColor }}
                  >
                    Arrived
                  </div>
                </div>
              </div>
            )}

            <div className="flex gap-2">
              <button
                onClick={save}
                disabled={saving}
                className="flex-1 px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white rounded disabled:opacity-50"
              >
                {saving ? 'Saving...' : 'Save Branding'}
              </button>
              <button
                onClick={() => setShowModal(false)}
                className="px-4 py-2 bg-gray-600 hover:bg-gray-500 text-white rounded"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
